### ISSUE TITLE
返回结果无内容

### ISSUE THREAD

**Issue by lixh00** [Jiabinone/notdiamond2api#1]
![image](https://github.com/user-attachments/assets/9fdfcc76-3f20-4c0f-b713-4077ec165d67)

**Comment by Jiabinone** [comment]
昨天好像是崩了,今天应该可以了

**Comment by lixh00** [comment]
![image](https://github.com/user-attachments/assets/8f8c897b-31c8-4d83-a1cc-5fb7e72c3f30)

还是不太对劲，复制的`next-chat`的值有什么讲究吗？随便复制哪个请求的都可以还是需要特定的请求？

**Comment by Jiabinone** [comment]
next-action 的值你需要在浏览器发起一次提问,找到提问的那个请求,在请求头找就行.

**Comment by 3377** [comment]
> ![image](https://private-user-images.githubusercontent.com/72033265/364671920-8f8c897b-31c8-4d83-a1cc-5fb7e72c3f30.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjU1NDM3MTEsIm5iZiI6MTcyNTU0MzQxMSwicGF0aCI6Ii83MjAzMzI2NS8zNjQ2NzE5MjAtOGY4Yzg5N2ItMzFjOC00ZDgzLWExY2MtNWZiN2U3MmMzZjMwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MDUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTA1VDEzMzY1MVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTlhYzZjOWNmZDk4MGYwNDA3YzVkMzFiMDdjYzUzYjIwZTg5NmNlNjA4Nzg5ZGRhMTFjNWUwODU2ODAyM2JjMzQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.2KNV4CdDsh5xFgyf2bmpeghTtYL1KQHW3ImUSqNqU0s)
> 
> 还是不太对劲，复制的`next-action`的值有什么讲究吗？随便复制哪个请求的都可以还是需要特定的请求？

你搞定了吗。可以对话不

**Comment by Jiabinone** [comment]
> > ![image](https://private-user-images.githubusercontent.com/72033265/364671920-8f8c897b-31c8-4d83-a1cc-5fb7e72c3f30.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjU1NDM3MTEsIm5iZiI6MTcyNTU0MzQxMSwicGF0aCI6Ii83MjAzMzI2NS8zNjQ2NzE5MjAtOGY4Yzg5N2ItMzFjOC00ZDgzLWExY2MtNWZiN2U3MmMzZjMwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MDUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTA1VDEzMzY1MVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTlhYzZjOWNmZDk4MGYwNDA3YzVkMzFiMDdjYzUzYjIwZTg5NmNlNjA4Nzg5ZGRhMTFjNWUwODU2ODAyM2JjMzQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.2KNV4CdDsh5xFgyf2bmpeghTtYL1KQHW3ImUSqNqU0s)
> 
> > 
> 
> > 还是不太对劲，复制的`next-action`的值有什么讲究吗？随便复制哪个请求的都可以还是需要特定的请求？
> 
> 
> 
> 你搞定了吗。可以对话不

可以的

**Comment by venbow** [comment]
刚刚试了下，我也是返回空值

**Comment by lixh00** [comment]
它有好几个请求，我应该复制哪个诶？

![image](https://github.com/user-attachments/assets/3240b8bd-86c1-4f44-8a9f-7789a2bb33b1)
![image](https://github.com/user-attachments/assets/d641dee3-e879-4cda-ae90-5d2d8e026acc)
![image](https://github.com/user-attachments/assets/a01e5341-6a19-4dfa-a504-a0b397ea085e)
![image](https://github.com/user-attachments/assets/7c0051e5-4e38-43a1-a3ff-855ae737332e)


> next-action 的值你需要在浏览器发起一次提问,找到提问的那个请求,在请求头找就行.

**Comment by Jiabinone** [comment]
> 它有好几个请求，我应该复制哪个诶？
> 
> ![image](https://private-user-images.githubusercontent.com/72033265/364995729-3240b8bd-86c1-4f44-8a9f-7789a2bb33b1.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjU1OTEyNDYsIm5iZiI6MTcyNTU5MDk0NiwicGF0aCI6Ii83MjAzMzI2NS8zNjQ5OTU3MjktMzI0MGI4YmQtODZjMS00ZjQ0LThhOWYtNzc4OWEyYmIzM2IxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MDYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTA2VDAyNDkwNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWJmNTM5MGIzMzEzODYxMGY2NjExOWE2Y2E4MDQ1OTNmMDVlMDM3OTczMDczMWFkMWU2NmE5YWExODlhYzU1MmQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.HlybTopDmUfK0Gbtd-Vigj8zNAt0N5nTymVn8pn8KR4) ![image](https://private-user-images.githubusercontent.com/72033265/364995737-d641dee3-e879-4cda-ae90-5d2d8e026acc.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjU1OTEyNDYsIm5iZiI6MTcyNTU5MDk0NiwicGF0aCI6Ii83MjAzMzI2NS8zNjQ5OTU3MzctZDY0MWRlZTMtZTg3OS00Y2RhLWFlOTAtNWQyZDhlMDI2YWNjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MDYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTA2VDAyNDkwNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTE0M2MxOGEyOGJiM2Q4M2JlZDRmMDIzMTJkYTAyYjhmYTMyYWQwNzIxMTM3N2UwOTVlOTQ1ZGZmMzA3M2IzNzkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.PrwVJWenYNErNUojcP1EUujt3sfV1DdRKMeKRjDtJZ8) ![image](https://private-user-images.githubusercontent.com/72033265/364995758-a01e5341-6a19-4dfa-a504-a0b397ea085e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjU1OTEyNDYsIm5iZiI6MTcyNTU5MDk0NiwicGF0aCI6Ii83MjAzMzI2NS8zNjQ5OTU3NTgtYTAxZTUzNDEtNmExOS00ZGZhLWE1MDQtYTBiMzk3ZWEwODVlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MDYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTA2VDAyNDkwNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWViZGU0MWM1ZTJlNGRhNjIxNWE5YzM5Y2M2YjQ4YmY0ZmQyZWM5MWZjMzJmNjk4MjA5OTA0MWY4ZDJjMjY3MmQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.d9hvWLU08OKyu9vliHhC4FBUPBHwIMTIL_M36nhzKVA) ![image](https://private-user-images.githubusercontent.com/72033265/364995807-7c0051e5-4e38-43a1-a3ff-855ae737332e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjU1OTEyNDYsIm5iZiI6MTcyNTU5MDk0NiwicGF0aCI6Ii83MjAzMzI2NS8zNjQ5OTU4MDctN2MwMDUxZTUtNGUzOC00M2ExLWEzZmYtODU1YWU3MzczMzJlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MDYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTA2VDAyNDkwNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTNkOTEzNDUyNGVkNDg5MWFiNTU1MjlkNzkxZDBjMjFiOTdkMGFlMmZhZjk1MmZhODY2N2I4MGQyOGNmMDBjOTgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.AMTK5FIQ2XBtWVn_7rBqBnYBzffJCwKSZAntxqh3rUc)
> 
> > next-action 的值你需要在浏览器发起一次提问,找到提问的那个请求,在请求头找就行.

![CleanShot 2024-09-06 at 10 49 26@2x](https://github.com/user-attachments/assets/6064acc5-c0c0-4779-9598-15db76439d04)
这个

**Comment by lixh00** [comment]
![image](https://github.com/user-attachments/assets/cc931987-5df2-44b5-a48a-d21420fc759b)
好好好，可以了可以了，感谢大佬！！
