### ISSUE TITLE
流式输出不完整

### ISSUE THREAD

**Issue by Payne-Wang** [Jiabinone/notdiamond2api#10]
大佬好，感谢提供的工具。

使用过程中发现，流式输出的内容有丢失，比如下方的首字"如"丢失，同时部分情况下还会出现中间字丢失，特别是写代码时，可能出现一些低级错误：丢括号、丢参数等。不知是否有方法可以优化！

![image](https://github.com/user-attachments/assets/f5c9d000-a737-456a-9555-9e88093b52cf)

谢谢大佬的工具！

**Comment by Jiabinone** [comment]
感谢提醒,我会尝试复现

**Comment by Jiabinone** [comment]
能告知你使用的模型吗,还有是否经过new api 之类的中转

**Comment by Payne-Wang** [comment]
大佬，我使用的是C3.5模型，经过one api转发

**Comment by Jiabinone** [comment]
> 大佬，我使用的是C3.5模型，经过one api转发

感觉这不是我的问题

**Comment by Payne-Wang** [comment]
> > 大佬，我使用的是C3.5模型，经过one api转发
> 
> 感觉这不是我的问题

好像是的，看论坛好像说是钻石自己的流式输出问题。

**Comment by Jiabinone** [comment]
> > > 大佬，我使用的是C3.5模型，经过one api转发
> > 
> > 
> > 感觉这不是我的问题
> 
> 好像是的，看论坛好像说是钻石自己的流式输出问题。

已经解决
