### ISSUE TITLE
能否添加多账号管理

### ISSUE THREAD

**Issue by 2328760190** [Jiabinone/notdiamond2api#11]
大佬能不能添加一个多账号管理获得更高的并发?

**Comment by QingyeSC** [comment]
。。。。。。

**Comment by 2328760190** [comment]
?

**Comment by Jiabinone** [comment]
> 大佬能不能添加一个多账号管理获得更高的并发?

这本身就已经支持多并发了啊

**Comment by 2328760190** [comment]
不够用😅，支持下么佬😘

在 2024-09-17 13:58:14，"Liz Nelly" ***@***.***> 写道：


大佬能不能添加一个多账号管理获得更高的并发?

这本身就已经支持多并发了啊

**Comment by Jiabinone** [comment]
> 不够用😅，支持下么佬😘 在 2024-09-17 13:58:14，"Liz Nelly" ***@***.***> 写道： 大佬能不能添加一个多账号管理获得更高的并发? 这本身就已经支持多并发了啊 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread.Message ID: ***@***.***>

你这是搞什么的,自己还不够用啊
