### ISSUE TITLE
Feature Request: Add API key to protect unauthorized API calls.

### ISSUE THREAD

**Issue by BuiltByLou** [Jiabinone/notdiamond2api#12]
I've forked your project and added protection to unauthorized API calls with the implementation of  API KEY.
This might be an easy and valuable enhancement to the project.

I define the Api key in the environment variables. 
in the code, I used the same same method as openAI to keep compatibility

**Comment by Jiabinone** [comment]
Now supported

**Comment by LuisBeOnline** [comment]
thank you :)
