### ISSUE TITLE
登录和刷新令牌请求错误 出错

### ISSUE THREAD

**Issue by ench2** [Jiabinone/notdiamond2api#19]
[root@localhost notdiamond2api]# docker logs notdiamond2api -f
ERROR:auth_utils:登录请求错误: HTTPSConnectionPool(host='spuckhogycrxcbomznwo.supabase.co', port=443): Max retries exceeded with url: /auth/v1/token?grant_type=password (Caused by SSLError(SSLZeroReturnError(6, 'TLS/SSL connection has been closed (EOF) (_ssl.c:1147)')))
WARNING:auth_utils:未找到匹配的脚本标签

刷新令牌请求错误: HTTPSConnectionPool(host='spuckhogycrxcbomznwo.supabase.co', port=443): Max retries exceeded with url: /auth/v1/token?grant_type=refresh_token (Caused by SSLError(SSLZeroReturnError(6, 'TLS/SSL connection has been closed (EOF) (_ssl.c:1147)')))
ERROR:auth_utils:登录请求错误: HTTPSConnectionPool(host='spuckhogycrxcbomznwo.supabase.co', port=443): Max retries exceeded with url: /auth/v1/token?grant_type=password (Caused by SSLError(SSLZeroReturnError(6, 'TLS/SSL connection has been closed (EOF) (_ssl.c:1147)')))

**Comment by Jiabinone** [comment]
> [root@localhost notdiamond2api]# docker logs notdiamond2api -f
> 
> ERROR:auth_utils:登录请求错误: HTTPSConnectionPool(host='spuckhogycrxcbomznwo.supabase.co', port=443): Max retries exceeded with url: /auth/v1/token?grant_type=password (Caused by SSLError(SSLZeroReturnError(6, 'TLS/SSL connection has been closed (EOF) (_ssl.c:1147)')))
> 
> WARNING:auth_utils:未找到匹配的脚本标签
> 
> 
> 
> 刷新令牌请求错误: HTTPSConnectionPool(host='spuckhogycrxcbomznwo.supabase.co', port=443): Max retries exceeded with url: /auth/v1/token?grant_type=refresh_token (Caused by SSLError(SSLZeroReturnError(6, 'TLS/SSL connection has been closed (EOF) (_ssl.c:1147)')))
> 
> ERROR:auth_utils:登录请求错误: HTTPSConnectionPool(host='spuckhogycrxcbomznwo.supabase.co', port=443): Max retries exceeded with url: /auth/v1/token?grant_type=password (Caused by SSLError(SSLZeroReturnError(6, 'TLS/SSL connection has been closed (EOF) (_ssl.c:1147)')))

关闭代理再试
