### ISSUE TITLE
400错误

### ISSUE THREAD

**Issue by 3377** [Jiabinone/notdiamond2api#2]
![image](https://github.com/user-attachments/assets/e596da9e-0182-403a-88de-1f14ad6521b6)

**Comment by Jiabinone** [comment]
昨天是不行,今天好了.你再试下

**Comment by 3377** [comment]
刚测试了，还是400,有什么需要注意的地方吗

**Comment by 3377** [comment]
试过各种方法，重新换了2个值，重新编译，请求还是400。

**Comment by Jiabinone** [comment]
> > 试过各种方法，重新换了2个值，重新编译，请求还是400。
> 
> 你拉去最新代码，试下，我刚才还在用呢。

你需要写入两个值到文件中，具体你看下 md 文档

**Comment by 3377** [comment]
两个值，cookies和next_action呗，我重新登录又填了一遍。我代码都拉到本地了。测试还是不行额。tg，drfyup。要不你远程调试看看？环境都现成的

**Comment by Jiabinone** [comment]
> 两个值，cookies和next_action呗，我重新登录又填了一遍。我代码都拉到本地了。测试还是不行额。tg，drfyup。要不你远程调试看看？环境都现成的

怪哉，明天给你看下

**Comment by 3377** [comment]
> > 两个值，cookies和next_action呗，我重新登录又填了一遍。我代码都拉到本地了。测试还是不行额。tg，drfyup。要不你远程调试看看？环境都现成的
> 
> 怪哉，明天给你看下

现在方便看下吗？。。。明天不一定有环境折腾了

**Comment by Jiabinone** [comment]
> > > 两个值，cookies和next_action呗，我重新登录又填了一遍。我代码都拉到本地了。测试还是不行额。tg，drfyup。要不你远程调试看看？环境都现成的
> 
> > 
> 
> > 怪哉，明天给你看下
> 
> 
> 
> 现在方便看下吗？。。。明天不一定有环境折腾了

下班没电脑

**Comment by 3377** [comment]
> > > > 两个值，cookies和next_action呗，我重新登录又填了一遍。我代码都拉到本地了。测试还是不行额。tg，drfyup。要不你远程调试看看？环境都现成的
> > 
> > 
> > > 
> > 
> > 
> > > 怪哉，明天给你看下
> > 
> > 
> > 现在方便看下吗？。。。明天不一定有环境折腾了
> 
> 下班没电脑

方便不，看一下。

**Comment by Jiabinone** [comment]
> > > > > 两个值，cookies和next_action呗，我重新登录又填了一遍。我代码都拉到本地了。测试还是不行额。tg，drfyup。要不你远程调试看看？环境都现成的
> > > 
> > > 
> > > > 
> > > 
> > > 
> > > > 怪哉，明天给你看下
> > > 
> > > 
> > > 现在方便看下吗？。。。明天不一定有环境折腾了
> > 
> > 
> > 下班没电脑
> 
> 方便不，看一下。

可以的

**Comment by 3377** [comment]
> > > > > > 两个值，cookies和next_action呗，我重新登录又填了一遍。我代码都拉到本地了。测试还是不行额。tg，drfyup。要不你远程调试看看？环境都现成的
> > > > 
> > > > 
> > > > > 
> > > > 
> > > > 
> > > > > 怪哉，明天给你看下
> > > > 
> > > > 
> > > > 现在方便看下吗？。。。明天不一定有环境折腾了
> > > 
> > > 
> > > 下班没电脑
> > 
> > 
> > 方便不，看一下。
> 
> 可以的

没法tg+我下，drfyup

**Comment by 3377** [comment]
{
    "choices": [
        {
            "finish_reason": "stop",
            "index": 0,
            "message": {
                "content": "",
                "role": "assistant"
            }
        }
    ],
    "created": 1725615974,
    "id": "chatcmpl-dc065fb0-60ac-42d8-9eb6-bc3cc0de22f8",
    "model": "gpt-4o",
    "object": "chat.completion",
    "system_fingerprint": "fp_c1db92dbe8",
    "usage": {
        "completion_tokens": 0,
        "prompt_tokens": 0,
        "total_tokens": 0
    }
}
用了最新的代码，返回如上，大哥是什么情况

**Comment by Jiabinone** [comment]
> {
> 
>     "choices": [
> 
>         {
> 
>             "finish_reason": "stop",
> 
>             "index": 0,
> 
>             "message": {
> 
>                 "content": "",
> 
>                 "role": "assistant"
> 
>             }
> 
>         }
> 
>     ],
> 
>     "created": 1725615974,
> 
>     "id": "chatcmpl-dc065fb0-60ac-42d8-9eb6-bc3cc0de22f8",
> 
>     "model": "gpt-4o",
> 
>     "object": "chat.completion",
> 
>     "system_fingerprint": "fp_c1db92dbe8",
> 
>     "usage": {
> 
>         "completion_tokens": 0,
> 
>         "prompt_tokens": 0,
> 
>         "total_tokens": 0
> 
>     }
> 
> }
> 
> 用了最新的代码，返回如上，大哥是什么情况

网页能正常对话吗，我怎么没遇到过这种情况，你尝试换一下系统部署，或者容器部署看看

**Comment by PennyJoly** [comment]
老哥，你加我微信c2500338766，我跟你说我发现的细节以及我能想到的一些解决对策
