### ISSUE TITLE
接口调用返回"Unauthorized"，重启之后能正常一会儿

### ISSUE THREAD

**Issue by lixh00** [Jiabinone/notdiamond2api#23]
> 使用Docker部署，机器在阿里云香港的。

返回结果如图所示
![image](https://github.com/user-attachments/assets/67c379f0-2d76-497d-8fd6-4dae15608fcf)

**Comment by Jiabinone** [comment]
会尝试修复

**Comment by lixh00** [comment]
大佬辛苦！！
