### ISSUE TITLE
worker下输出有乱码

### ISSUE THREAD

**Issue by 3377** [Jiabinone/notdiamond2api#24]
![image](https://github.com/user-attachments/assets/3a977239-5e0f-4212-8d55-1e519fac4381)

**Comment by Jiabinone** [comment]
什么ui

**Comment by 3377** [comment]
Cherry Studio 
llama-3.1-sonar-large-128k-online 这个模型，应该主要是模型的原因。openwebui也会这样。
![image](https://github.com/user-attachments/assets/be3fee69-4e68-4200-9935-ff09dbe0f3b4)

**Comment by 3377** [comment]
claude模型没问题

**Comment by Jiabinone** [comment]
估计是模型问题

**Comment by 3377** [comment]
> 估计是模型问题

不是模型问题，我用其他方式逆的没问题

**Comment by 3377** [comment]
这个能修复下吗?目前worker的速度最快~

**Comment by Jiabinone** [comment]
> 这个能修复下吗?目前worker的速度最快~

docker的速度也很快哦

**Comment by 3377** [comment]
还不错，挺高效的，什么时候加上多账号呀。一个账号使用有限吧

**Comment by Jiabinone** [comment]
> 还不错，挺高效的，什么时候加上多账号呀。一个账号使用有限吧

这个不会上,自用一个号足够
