### ISSUE TITLE
token刷新达到限速

### ISSUE THREAD

**Issue by krinlove99** [Jiabinone/notdiamond2api#27]
环境：workerjs部署，每天少于300次总调用
问题：调用claude系列模型时会触发login failed，但是调用其他模型就不会产生这一问题。

附日志：
"message": [
"Token refresh failed:",
"Too Many Requests"
],
"level": "error",
"timestamp": 1730970087205
},
{
"message": [
"Login failed:",
"Too Many Requests"
],

**Comment by clionertr** [comment]
在model_info.py添加即可  
```
    "claude-3-5-sonnet-20241022": {
        "provider": "anthropic",
        "mapping": "anthropic.claude-3-5-sonnet-20241022-v2:0"
```

**Comment by k2o333** [comment]
worker.js里没有 model_info.py
