### ISSUE TITLE
感觉用workers.js部署比docker部署的回复率低了不少

### ISSUE THREAD

**Issue by k2o333** [Jiabinone/notdiamond2api#31]
其他人有没有这个感觉，有没有人知道为何？有没有啥解决方案？

**Comment by Jiabinone** [comment]
回复率低是指什么

**Comment by k2o333** [comment]
用cline编程的时候，会反馈 
![image](https://github.com/user-attachments/assets/f8050e99-9879-4474-97c8-9a24830d6937)

用dify则直接不回复

**Comment by Jiabinone** [comment]
tokens肯定超了,还有就是不支持工具或函数调用. 不推荐用cline, 可以尝试下aider

**Comment by k2o333** [comment]
> 需要用openai格式的,还有就是不支持工具或函数调用. 不推荐用cline, 可以尝试下aider

确实是openai模式 。litellm调用几个workers.js轮询
两个都在用，aider消耗token少。
aider也经常遇到大模型回复0token

**Comment by Jiabinone** [comment]
那这就不清楚啦,我在用aider没遇到这个问题
