### ISSUE TITLE
这是返回的个啥玩意儿~[Error 1101]

### ISSUE THREAD

**Issue by lixh00** [Jiabinone/notdiamond2api#32]
![image](https://github.com/user-attachments/assets/e2e2102a-973d-46f4-9cc8-9b42aef7e4e2)

**Comment by lixh00** [comment]
看起来像是nd的服务挂了？

**Comment by Jiabinone** [comment]
这是啥,我也不清楚.也没见过啊

**Comment by lixh00** [comment]
> 这是啥,我也不清楚.也没见过啊

笑死，请求接口返回来的，看起来像是nd的服务出问题了，但是我直接打开他们网页又没得这个

**Comment by Ken288yzs1** [comment]
现在已经好了

**Comment by lixh00** [comment]
> 现在已经好了

好好好，看来确实是nd的问题。
