### ISSUE TITLE
触发cf，不知是什么bug还是限制

### ISSUE THREAD

**Issue by PennyJoly** [Jiabinone/notdiamond2api#34]
<!DOCTYPE html>

 <html class="no-js" lang="en-US"> 
<head>
<title>Worker threw exception | not-diamond-workers.t7-cc4.workers.dev | Cloudflare</title>
<meta charset="UTF-8" />
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
<meta http-equiv="X-UA-Compatible" content="IE=Edge" />
<meta name="robots" content="noindex, nofollow" />
<meta name="viewport" content="width=device-width,initial-scale=1" />
<link rel="stylesheet" id="cf_styles-css" href="/cdn-cgi/styles/cf.errors.css" />

<style>body{margin:0;padding:0}</style>

<script>
  if (!navigator.cookieEnabled) {
    window.addEventListener('DOMContentLoaded', function () {
      var cookieEl = document.getElementById('cookie-alert');
      cookieEl.style.display = 'block';
    })
  }
</script>

</head>
<body>
  <div id="cf-wrapper">
    <div class="cf-alert cf-alert-error cf-cookie-error" id="cookie-alert" data-translate="enable_cookies">Please enable cookies.</div>
    <div id="cf-error-details" class="cf-error-details-wrapper">
      <div class="cf-wrapper cf-header cf-error-overview">
        <h1>
          <span class="cf-error-type" data-translate="error">Error</span>
          <span class="cf-error-code">1101</span>
          <small class="heading-ray-id">Ray ID: xxxxxxxxx &bull; 2024-11-14 14:25:33 UTC</small>
        </h1>
        <h2 class="cf-subheadline" data-translate="error_desc">Worker threw exception</h2>
      </div>

      <section></section>

      <div class="cf-section cf-wrapper">
        <div class="cf-columns two">
          <div class="cf-column">
            <h2 data-translate="what_happened">What happened?</h2>
            <p>You've requested a page on a website (not-diamond-workers.t7-cc4.workers.dev) that is on the <a href="https://www.cloudflare.com/5xx-error-landing/" target="_blank">Cloudflare</a> network. An unknown error occurred while rendering the page.</p>
          </div>

          <div class="cf-column">
            <h2 data-translate="what_can_i_do">What can I do?</h2>
            <p><strong>If you are the owner of this website:</strong><br />you should <a href="https://www.cloudflare.com/login?utm_source=error_100x" target="_blank">login to Cloudflare</a> and check the error logs for not-diamond-workers.t7-cc4.workers.dev.</p>
          </div>

        </div>
      </div>

      <div class="cf-error-footer cf-wrapper w-240 lg:w-full py-10 sm:py-4 sm:px-8 mx-auto text-center sm:text-left border-solid border-0 border-t border-gray-300">
  <p class="text-13">
    <span class="cf-footer-item sm:block sm:mb-1">Cloudflare Ray ID: <strong class="font-semibold">8e27b9421b9ed487</strong></span>
    <span class="cf-footer-separator sm:hidden">&bull;</span>
    <span id="cf-footer-item-ip" class="cf-footer-item hidden sm:block sm:mb-1">
      Your IP:
      <button type="button" id="cf-footer-ip-reveal" class="cf-footer-ip-reveal-btn">Click to reveal</button>
      <span class="hidden" id="cf-footer-ip">xxxxxxx</span>
      <span class="cf-footer-separator sm:hidden">&bull;</span>
    </span>
    <span class="cf-footer-item sm:block sm:mb-1"><span>Performance &amp; security by</span> <a rel="noopener noreferrer" href="https://www.cloudflare.com/5xx-error-landing" id="brand_link" target="_blank">Cloudflare</a></span>

  </p>
  <script>(function(){function d(){var b=a.getElementById("cf-footer-item-ip"),c=a.getElementById("cf-footer-ip-reveal");b&&"classList"in b&&(b.classList.remove("hidden"),c.addEventListener("click",function(){c.classList.add("hidden");a.getElementById("cf-footer-ip").classList.remove("hidden")}))}var a=document;document.addEventListener&&a.addEventListener("DOMContentLoaded",d)})();</script>
</div>

    </div>
  </div>

  <script>

</script>

</body>
</html>

**Comment by Jiabinone** [comment]
没有遇到这个问题,可能是这几天有人公开做了多账号轮询,官方警惕了也有可能.

**Comment by PennyJoly** [comment]
> 没有遇到这个问题,可能是这几天有人公开做了多账号轮询,官方警惕了也有可能.

这几天是非常频繁的触发这个情况，stream无论设置没，都会有这个情况

**Comment by clionertr** [comment]
docker compos版本重启能解决，设置个n小时定时任务就好

**Comment by PennyJoly** [comment]
> docker compos版本重启能解决，设置个n小时定时任务就好

重新部署我也试过，还是会有这个问题。部署过后刚两分钟，就出发了这个情况了。所以您给出的这个定时任务重置，估计也不理想

**Comment by lixh00** [comment]
我最近也经常这样

**Comment by PennyJoly** [comment]
> 话说开Pro会触发cf这种咩？

好像还是会

**Comment by VTSTG233** [comment]
有木有办法，就是检测到cloudflare相关字输出，则直接返回错误码以及对应错误消息输出并停止输出cf的报错内容这样？
错误消息大致可以这样：当前对话出现错误，请联系管理员检查并更新配置

相关的消息输出这样

**Comment by PennyJoly** [comment]
> 有木有办法，就是检测到cloudflare相关字输出，则直接返回错误码以及对应错误消息输出并停止输出cf的报错内容这样？ 错误消息大致可以这样：当前对话出现错误，请联系管理员检查并更新配置
> 
> 相关的消息输出这样
这个得看作者了

**Comment by Jiabinone** [comment]
这是docker版的吗,抽空找个时间优化一下输出

**Comment by VTSTG233** [comment]
是滴 我是docker滴

**Comment by VTSTG233** [comment]
话说，直接cf的workers那搭建这个，会不会出现这种情况呢

**Comment by VTSTG233** [comment]
> 这是docker版的吗,抽空找个时间优化一下输出

好嘞

**Comment by Jiabinone** [comment]
> 话说，直接cf的workers那搭建这个，会不会出现这种情况呢

我暂时没有遇到过.
