### ISSUE TITLE
Max retries reached 重新部署后还是会有这个问题

### ISSUE THREAD

**Issue by PennyJoly** [Jiabinone/notdiamond2api#35]
如题，Max retries reached报错。 重新部署docker后还是会有这个问题

**Comment by Jiabinone** [comment]
可以检查一下账号密码是否正确,refresh token 能否正常获取

**Comment by PennyJoly** [comment]
> 可以检查一下账号密码是否正确,refresh token 能否正常获取

检查了，是可正常登录的，rt也能正常获取

**Comment by Jiabinone** [comment]
Max retries reached 这个报错跟网络可能有关系,你尝试换一个网络.推荐用海外的网络

**Comment by PennyJoly** [comment]
> Max retries reached 这个报错跟网络可能有关系,你尝试换一个网络.推荐用海外的网络

我服务器就在海外

**Comment by sofs2005** [comment]
diamond只支持文字对话，发图片过去就会报这个

**Comment by PennyJoly** [comment]
> diamond只支持文字对话，发图片过去就会报这个

怪不得呢
