### ISSUE TITLE
关于配额的问题

### ISSUE THREAD

**Issue by nekomiya-hinata** [Jiabinone/notdiamond2api#36]
有个疑惑，这个网站现在的配额是每天刷新还是固定的呢？我有个账号提示usage limit了，但是等了一天也没有恢复

**Comment by Doutianbao** [comment]
同款好奇

**Comment by PennyJoly** [comment]
我测试了几天，它现在好像变成固定的额度了。只要你达到它固定的额度，后面就只能用免费的模型。Pro的付费模型想使用只能开它的pro会员了

**Comment by PennyJoly** [comment]
但我开了会员后，还是会有cf的问题。想退款都退不了  - -

**Comment by nekomiya-hinata** [comment]
会员用国内银联卡可以开吗

> 我测试了几天，它现在好像变成固定的额度了。只要你达到它固定的额度，后面就只能用免费的模型。Pro的付费模型想使用只能开它的pro会员了

**Comment by PennyJoly** [comment]
> 会员用国内银联卡可以开吗
> 
> > 我测试了几天，它现在好像变成固定的额度了。只要你达到它固定的额度，后面就只能用免费的模型。Pro的付费模型想使用只能开它的pro会员了

是的，银联我不知道，我用的visa倒是开成功了

**Comment by k2o333** [comment]
固定配额大约多少？

**Comment by PennyJoly** [comment]
> 固定配额大约多少？也不是很清楚，貌似100次对话

**Comment by Jiabinone** [comment]
我也感觉到了,现在pro的模型限制挺厉害的.不过一些小模型不影响.
