### ISSUE TITLE
文生图模型啥时候可以加进去呀

### ISSUE THREAD

**Issue by k2o333** [Jiabinone/notdiamond2api#37]
![image](https://github.com/user-attachments/assets/3fce8fe2-c815-4218-9f5b-eea3b2f291f6)

能白嫖不错过哦

**Comment by Jiabinone** [comment]
这是什么模型

**Comment by k2o333** [comment]
![image](https://github.com/user-attachments/assets/56cc5bb0-4454-4fd7-b3df-14ed7bf4cc17)
notdiamond支持的几个模型，我忘了当时是哪两个了

**Comment by Jiabinone** [comment]
我看了下,好像工程还挺大的~~暂时还没时间弄
