### ISSUE TITLE
建议增加多个账号轮流循环

### ISSUE THREAD

**Issue by AthanaD** [Jiabinone/notdiamond2api#38]
RT

**Comment by Jiabinone** [comment]
没计划.本项目个人用用还是够的

**Comment by nekomiya-hinata** [comment]
个人使用还是够的

**Comment by QingyeSC** [comment]
觉得别弄了，这不是给号商用吗

**Comment by AthanaD** [comment]
> 现在免费账号都限额了吗.

现在一个账号一天只能用10次，没法玩了，所以多账号轮流循环势在必行，如果有批量注册机更优了

**Comment by k2o333** [comment]
别想了人家至少也会根据ip有一定限制

**Comment by Jiabinone** [comment]
多账号不打算考虑.如有这个需求,可以自行拉取代码,二次开发.workers的代码可以直接进行二开.

**Comment by sofs2005** [comment]
只有10次了吗，我刚知道这个才部署好就挂了啊

**Comment by sofs2005** [comment]
哪些是免费模型哪些是pro的？没找到说明

**Comment by Jiabinone** [comment]
> 哪些是免费模型哪些是pro的？没找到说明

好像对话模型都能用.就是次数有限制,
