### ISSUE TITLE
测试下来的情况是，cookie每过几分钟会失效，输出的接口就会是空的

### ISSUE THREAD

**Issue by PennyJoly** [Jiabinone/notdiamond2api#4]
测试下来的情况是，cookie每过几分钟会失效，输出的接口就会是空的，感觉结合着refeashToken来弄的话，应该能保活

**Comment by PennyJoly** [comment]
老哥，你加我微信c2500338766，我跟你说我发现的细节以及我能想到的一些解决对策

**Comment by Jiabinone** [comment]
> 测试下来的情况是，cookie每过几分钟会失效，输出的接口就会是空的，感觉结合着refeashToken来弄的话，应该能保活

我的用了几天了还可以啊，是不是有什么玄机在这里面

**Comment by PennyJoly** [comment]
> > 测试下来的情况是，cookie每过几分钟会失效，输出的接口就会是空的，感觉结合着refeashToken来弄的话，应该能保活
> 
> 我的用了几天了还可以啊，是不是有什么玄机在这里面

感觉是的
