### ISSUE TITLE
在docker里建好后打开显示无此连接

### ISSUE THREAD

**Issue by Homer-Max** [Jiabinone/notdiamond2api#41]
Not Found
The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.
请教一下，这是哪里出问题了

**Comment by Jiabinone** [comment]
暂时未知错误点.需要排查

**Comment by Jiabinone** [comment]
这是docker部署的吗

**Comment by Homer-Max** [comment]
> 这是docker部署的吗

是的，在docker里部署的

**Comment by Homer-Max** [comment]
* Debug mode: off

INFO:werkzeug:WARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.

 * Running on all addresses (0.0.0.0)

 * Running on http://127.0.0.1:3000

 * Running on http://172.17.0.8:3000

INFO:werkzeug:Press CTRL+C to quit

INFO:werkzeug:172.17.0.1 - - [01/Dec/2024 03:25:24] "GET / HTTP/1.1" 404 -

INFO:werkzeug:172.17.0.1 - - [01/Dec/2024 03:25:24] "GET /favicon.ico HTTP/1.1" 404 -

INFO:werkzeug:10.15.20.25 - - [01/Dec/2024 03:25:39] "GET / HTTP/1.1" 404 -

INFO:werkzeug:10.15.20.25 - - [01/Dec/2024 03:25:39] "GET /favicon.ico HTTP/1.1" 404 -

**Comment by Jiabinone** [comment]
你是否使用了nginx之类的转发呢,你删除镜像重新拉取试下.使用latest标签
