### ISSUE TITLE
好像每过一个多小时就会挂掉，重启一下就好了

### ISSUE THREAD

**Issue by sofs2005** [Jiabinone/notdiamond2api#42]
是不是token刷新的时间太长了啊？
另外能不能说一下哪几个模型是可以免费用的？我试下来4omini，4olatest，haiku是OK的，其他觉得可能没这几个好用就还没试

**Comment by Jiabinone** [comment]
我就用一个模型~~其他模型都不怎么用. claude 3.5

**Comment by sofs2005** [comment]
> 我就用一个模型~~其他模型都不怎么用. claude 3.5

claude haiku也变成pro模型了

**Comment by sofs2005** [comment]
好像被撸秃了，网页版都超时了。。

**Comment by sofs2005** [comment]
> 我就用一个模型~~其他模型都不怎么用. claude 3.5

老板你看一下gpt4o模型的名字是什么，我用latest和4o都说已经超限了，但是从页面看应该有个4o是能用的

**Comment by sofs2005** [comment]
好了，4o正式挂掉，免费就剩4个了

**Comment by sofs2005** [comment]
结束，免费每天20次额度了
