### ISSUE TITLE
 Empty Response from /v1/chat/completions 

### ISSUE THREAD

**Issue by LuisBeOnline** [Jiabinone/notdiamond2api#5]
I am experiencing an issue when posting to the /v1/chat/completions endpoint with any model. 

Below are the details of the request and the response received.

Request:
```
{
  "model": "gpt-4o-mini",
  "messages": [
    {
      "role": "user",
      "content": "what's the deepest ocean on earth?"
    }
  ],
  "stream": false
}
```

API Response:
```
{
    "choices": [
        {
            "finish_reason": "stop",
            "index": 0,
            "message": {
                "content": "",
                "role": "assistant"
            }
        }
    ],
    "created": 1725969063,
    "id": "chatcmpl-a7539c68-4d40-4075-9473-2e9d8e64e723",
    "model": "gpt-4o-mini",
    "object": "chat.completion",
    "system_fingerprint": "fp_27ddf3a618",
    "usage": {
        "completion_tokens": 0,
        "prompt_tokens": 19,
        "total_tokens": 19
    }
}
```

Details:

The response from the API contains an empty content field in the message object, despite a valid prompt being sent.
I have tested this with cookies and next-actions both in the environment and in the file.

**Comment by Jiabinone** [comment]
Your cookie and next-action should be retrieved from the request headers in the request body containing the message field from the notdiamond conversation, otherwise, it may result in an empty response.

**Comment by LuisBeOnline** [comment]
![Screenshot 2024-09-11 164254](https://github.com/user-attachments/assets/4fd624ba-1f19-4514-9167-10ffbc243136)

I'm assuming your printscreen is from playload tab. the image above is the closest I get to your what you shared in the image.
Even get the Cookie and Next-Action from here the message returned empty
