### ISSUE TITLE
next-action的值在不同请求中不一样

### ISSUE THREAD

**Issue by k2o333** [Jiabinone/notdiamond2api#7]
![image](https://github.com/user-attachments/assets/1d5f30e2-1db6-4298-a53e-eff78ed6b2ee)
![image](https://github.com/user-attachments/assets/425a19ed-529c-41b9-8030-43028b64921d)

next-action的值在不同请求中不一样，难道都能用？

**Comment by Jiabinone** [comment]
是的,要找对话的那条

**Comment by Jiabinone** [comment]
其他的不能用

**Comment by k2o333** [comment]
一对话就起来n条，我怎么确定哪条是对话的？我两个模型同时对话，所以只要找值一样的就肯定是对话的两条？
